name: Test Dispatch

on:
  workflow_dispatch:
    inputs:
      test_input:
        description: 'Test input for workflow dispatch'
        required: true
        default: 'default-value'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Print input
        run: echo "Input value: ${{ github.event.inputs.test_input }}"
